package com.Server.repository.entity;

public enum FactorsWorkplaceSafety {
    QUALITY_OF_WORK_EQUIPMENT,
    THE_WORKER_HIMSELF,
    WAY_AND_SPEED_PERFORMING_WORK_OPERATIONS,
    INJURIES_AND_ACCIDENTS_THAT_HAVE_OCCURRED,
    MANAGEMENT,
    PERSON_IN_CHARGE_OF_SAFETY_AT_WORK,
}
