spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  accessTokenExpiryMs: 60000       # 1 minute (Access token expires quickly)
  refreshTokenExpiryMs: 3600000    # 1 hour (Refresh token expires after 1 hour)

cors:
  allowedOrigins: "http://localhost:5173"
  allowedMethods: "*"
  allowedHeaders: "*"

