server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: clupascu923@gmail.com
    password: rvpnjmtccwdzeqvx
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8

jwt:
  accessTokenExpiryMs: 60000       # 1 minute (Access token expires quickly)
  refreshTokenExpiryMs: 3600000    # 1 hour (Refresh token expires after 1 hour)

cors:
  allowedOrigins: "http://localhost:5173"
  allowedMethods: "*"
  allowedHeaders: "*"